<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteRepository extends EntityRepository
{
    public function AllCarteRandom()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a.id , a.value, b.category FROM carte AS a INNER JOIN categorie AS b ON a.categorie_id=b.id  order by RAND() LIMIT 10'
            )
            ->getResult();
    }
}
