app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
bundle_route:
    resource: "@AppBundle/Resources/config/routing.yml"

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

login_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Security:logout }