AppBundle\Entity\Categorie:
    type: entity
    table: categorie
    repositoryClass: AppBundle\Repository\CategorieRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        category:
            type: string
            length: '20'        
    lifecycleCallbacks: {  }
